In [8]:
import numpy as np
import matplotlib.pyplot as plt
from PIL import Image
import glob
import cv2
import os,shutil
import random
import time

END = 3
START = 2
WALL = 0
EMPTY = 1

img = cv2.imread("maze1.png")
maze = np.ones([15,15])

def translate(vectorRGB):
    if(vectorRGB[0] > 150 and vectorRGB[1] > 150 and vectorRGB[2] > 150):
        return EMPTY
    if(vectorRGB[0] < 150 and vectorRGB[1] > 150 and vectorRGB[2] < 150):
        return END
    if(vectorRGB[0] < 150 and vectorRGB[1] < 150 and vectorRGB[2] > 150):
        return START
    if(vectorRGB[0] == 0 and vectorRGB[1] == 0 and vectorRGB[2] == 0):
        return WALL

for i,row in enumerate(img):
    for j,pixel in enumerate(row):
        label = translate(pixel)
        maze[i][j] = float(label)
print(maze)
print()
print()

file = open("maze1.txt","w") 

for i,row in enumerate(maze):
    for j,value in enumerate(row):
        if(value == START):
            print("initial_state(  maze, p(%i,%i)  )."%(j,i) )
            file.write("initial_state(  maze, p(%i,%i)  ).\n"%(j,i) ) 

print()
file.write("\n")
for i,row in enumerate(maze):
    for j,value in enumerate(row):
        if(value == END):
            print("final_state(  maze, p(%d,%d)  )."%(j,i) )
            file.write("final_state(  maze, p(%d,%d)  ).\n"%(j,i) )
print()
file.write("\n")
print("c(X, Y, wall) :-")
file.write("c(X, Y, wall) :-\n")
for i,row in enumerate(maze):
    for j,value in enumerate(row):
        if(value == WALL):
            print("\tX = %d, Y = %d\n\t;"%(i,j) )
            file.write("\tX = %d, Y = %d\n\t;\n"%(i,j) )
print("\tX > %d; Y > %d."%(len(maze[0]), len(maze[0])) )  
file.write("\tX > %d; Y > %d.\n"%(len(maze[0]), len(maze[0])) )

file.close()

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 2. 0. 1. 1. 1. 0. 1. 1. 1. 0. 1. 1. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 0. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 1. 1. 0. 1. 0. 1. 1. 1. 0.]
 [0. 1. 0. 1. 0. 0. 0. 0. 0. 1. 0. 0. 0. 1. 0.]
 [0. 1. 0. 1. 1. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1. 0. 0. 0. 0. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 3. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


initial_state(  maze, p(1,1)  ).

final_state(  maze, p(13,13)  ).

c(X, Y, wall) :-
	X = 0, Y = 0
	;
	X = 0, Y = 1
	;
	X = 0, Y = 2
	;
	X = 0, Y = 3
	;
	X = 0, Y = 4
	;
	X = 0, Y = 5
	;
	X = 0, Y = 6
	;
	X = 0, Y = 7
	;
	X = 0, Y = 8
	;
	X = 0, Y = 9
	;
	X = 0, Y = 10
	;
	X =